---

- name: Ensure MariaDB paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ devture_mariadb_uid }}"
    group: "{{ devture_mariadb_gid }}"
  with_items:
    - "{{ devture_mariadb_base_path }}"
    - "{{ devture_mariadb_data_path }}"

- name: Ensure MariaDB image is pulled
  docker_image:
    name: "{{ devture_mariadb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure MariaDB configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ devture_mariadb_base_path }}/{{ item }}"
    owner: "{{ devture_mariadb_uid }}"
    group: "{{ devture_mariadb_gid }}"
    mode: 0640
  with_items:
    - "env"
    - "my.cnf"

- name: Ensure MariaDB scripts created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}.j2"
    dest: "{{ devture_mariadb_bin_path }}/bin/{{ item }}"
    mode: 0750
  with_items:
    - cli
    - dump

- name: Ensure MariaDB service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/mariadb.service.j2"
    dest: "/etc/systemd/system/{{ devture_mariadb_identifier }}.service"
    mode: 0640
  register: devture_mariadb_systemd_service_result

- name: Ensure systemd reloaded after MariaDB service installation
  service:
    daemon_reload: yes
  when: devture_mariadb_systemd_service_result.changed
